[2025-05-08T22:25:42.029+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T22:25:42.074+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.normalize_and_clean_data manual__2025-05-08T22:12:11.230444+00:00 [queued]>
[2025-05-08T22:25:42.098+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.normalize_and_clean_data manual__2025-05-08T22:12:11.230444+00:00 [queued]>
[2025-05-08T22:25:42.100+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-05-08T22:25:42.130+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): normalize_and_clean_data> on 2025-05-08 22:12:11.230444+00:00
[2025-05-08T22:25:42.152+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=657) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-08T22:25:42.155+0000] {standard_task_runner.py:72} INFO - Started process 672 to run task
[2025-05-08T22:25:42.156+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'normalize_and_clean_data', 'manual__2025-05-08T22:12:11.230444+00:00', '--job-id', '919', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmp44g6ojuz']
[2025-05-08T22:25:42.158+0000] {standard_task_runner.py:105} INFO - Job 919: Subtask normalize_and_clean_data
[2025-05-08T22:25:42.270+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.normalize_and_clean_data manual__2025-05-08T22:12:11.230444+00:00 [running]> on host ff2d23694728
[2025-05-08T22:25:42.486+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='elkhalfimaryame@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='normalize_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T22:12:11.230444+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T22:12:11.230444+00:00'
[2025-05-08T22:25:42.490+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-08T22:25:42.491+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-08T22:25:42.492+0000] {logging_mixin.py:190} INFO - Current task name:normalize_and_clean_data state:running start_date:2025-05-08 22:25:42.075809+00:00
[2025-05-08T22:25:42.495+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-08T22:25:42.496+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-08T22:25:42.517+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-08T22:25:42.538+0000] {warnings.py:112} WARNING - /opt/***/dags/storeData.py:398: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM review.raw_reviews", conn)

[2025-05-08T22:25:45.774+0000] {warnings.py:112} WARNING - /opt/***/dags/storeData.py:428: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-05-08T22:25:45.964+0000] {logging_mixin.py:190} INFO - Data normalized and cleaned successfully.
[2025-05-08T22:25:45.969+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-08T22:25:45.985+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-08T22:25:45.986+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=normalize_and_clean_data, run_id=manual__2025-05-08T22:12:11.230444+00:00, execution_date=20250508T221211, start_date=20250508T222542, end_date=20250508T222545
[2025-05-08T22:25:46.042+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-08T22:25:46.043+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-08T22:25:46.044+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-08 22:23:32.243800+00:00
[2025-05-08T22:25:46.045+0000] {logging_mixin.py:190} INFO - Task hostname:ff2d23694728 operator:PythonOperator
[2025-05-08T22:25:46.080+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-08T22:25:46.138+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-08T22:25:46.144+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
