[2025-05-08T21:53:22.878+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T21:53:22.918+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.export_to_csv manual__2025-05-08T21:43:14.329156+00:00 [queued]>
[2025-05-08T21:53:22.944+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.export_to_csv manual__2025-05-08T21:43:14.329156+00:00 [queued]>
[2025-05-08T21:53:22.948+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-08T21:53:22.978+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): export_to_csv> on 2025-05-08 21:43:14.329156+00:00
[2025-05-08T21:53:22.998+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=514) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-08T21:53:23.004+0000] {standard_task_runner.py:72} INFO - Started process 529 to run task
[2025-05-08T21:53:23.005+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'export_to_csv', 'manual__2025-05-08T21:43:14.329156+00:00', '--job-id', '902', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpb55j67a8']
[2025-05-08T21:53:23.007+0000] {standard_task_runner.py:105} INFO - Job 902: Subtask export_to_csv
[2025-05-08T21:53:23.099+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.export_to_csv manual__2025-05-08T21:43:14.329156+00:00 [running]> on host f90cb465d7e0
[2025-05-08T21:53:23.301+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='elkhalfimaryame@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='export_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T21:43:14.329156+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T21:43:14.329156+00:00'
[2025-05-08T21:53:23.305+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-08T21:53:23.307+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-08T21:53:23.308+0000] {logging_mixin.py:190} INFO - Current task name:export_to_csv state:running start_date:2025-05-08 21:53:22.924440+00:00
[2025-05-08T21:53:23.309+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-08T21:53:23.311+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-08T21:53:23.333+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-08T21:53:23.465+0000] {warnings.py:112} WARNING - /opt/***/dags/storeData.py:98: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-05-08T21:53:23.725+0000] {logging_mixin.py:190} INFO - ✅ Données exportées avec succès vers reviews_export.csv
[2025-05-08T21:53:23.729+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-08T21:53:23.751+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-08T21:53:23.753+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=export_to_csv, run_id=manual__2025-05-08T21:43:14.329156+00:00, execution_date=20250508T214314, start_date=20250508T215322, end_date=20250508T215323
[2025-05-08T21:53:23.844+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-08T21:53:23.848+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-08T21:53:23.850+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-08 21:43:14.370818+00:00
[2025-05-08T21:53:23.851+0000] {logging_mixin.py:190} INFO - Task hostname:f90cb465d7e0 operator:PythonOperator
[2025-05-08T21:53:23.909+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-08T21:53:23.981+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-08T21:53:24.005+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
