[2025-05-04T15:58:10.899+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-04T15:58:10.941+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.export_to_csv manual__2025-05-04T15:47:55.314508+00:00 [queued]>
[2025-05-04T15:58:10.964+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.export_to_csv manual__2025-05-04T15:47:55.314508+00:00 [queued]>
[2025-05-04T15:58:10.983+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 4
[2025-05-04T15:58:11.010+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): export_to_csv> on 2025-05-04 15:47:55.314508+00:00
[2025-05-04T15:58:11.033+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=542) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-04T15:58:11.037+0000] {standard_task_runner.py:72} INFO - Started process 557 to run task
[2025-05-04T15:58:11.039+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'export_to_csv', 'manual__2025-05-04T15:47:55.314508+00:00', '--job-id', '441', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpcb6wz68o']
[2025-05-04T15:58:11.042+0000] {standard_task_runner.py:105} INFO - Job 441: Subtask export_to_csv
[2025-05-04T15:58:11.129+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.export_to_csv manual__2025-05-04T15:47:55.314508+00:00 [running]> on host 8280c28b7f0f
[2025-05-04T15:58:11.310+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='export_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T15:47:55.314508+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T15:47:55.314508+00:00'
[2025-05-04T15:58:11.313+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-04T15:58:11.315+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-04T15:58:11.316+0000] {logging_mixin.py:190} INFO - Current task name:export_to_csv state:running start_date:2025-05-04 15:58:10.942611+00:00
[2025-05-04T15:58:11.317+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-04T15:58:11.317+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-04T15:58:11.336+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-04T15:58:11.357+0000] {warnings.py:112} WARNING - /opt/***/dags/storeData.py:72: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

[2025-05-04T15:58:11.407+0000] {logging_mixin.py:190} INFO - ✅ Données exportées avec succès vers reviews_export.csv
[2025-05-04T15:58:11.409+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-04T15:58:11.428+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-04T15:58:11.432+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews, task_id=export_to_csv, run_id=manual__2025-05-04T15:47:55.314508+00:00, execution_date=20250504T154755, start_date=20250504T155810, end_date=20250504T155811
[2025-05-04T15:58:11.493+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-05-04T15:58:11.495+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-05-04T15:58:11.496+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews queued_at:2025-05-04 15:58:03.239148+00:00
[2025-05-04T15:58:11.498+0000] {logging_mixin.py:190} INFO - Task hostname:8280c28b7f0f operator:PythonOperator
[2025-05-04T15:58:11.537+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-04T15:58:11.577+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-04T15:58:11.583+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
