[2025-04-21T23:36:15.407+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T23:36:15.457+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews_pipeline.model_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-21T23:36:15.492+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews_pipeline.model_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-21T23:36:15.505+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-21T23:36:15.535+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): model_data> on 2025-04-04 00:00:00+00:00
[2025-04-21T23:36:15.560+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-21T23:36:15.564+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews_pipeline', 'model_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmp0zt1ld4k']
[2025-04-21T23:36:15.566+0000] {standard_task_runner.py:72} INFO - Started process 349 to run task
[2025-04-21T23:36:15.567+0000] {standard_task_runner.py:105} INFO - Job 54: Subtask model_data
[2025-04-21T23:36:15.706+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews_pipeline.model_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host 95fe2406fe61
[2025-04-21T23:36:15.876+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews_pipeline' AIRFLOW_CTX_TASK_ID='model_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-21T23:36:15.879+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-21T23:36:15.880+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-21T23:36:15.881+0000] {logging_mixin.py:190} INFO - Current task name:model_data state:running start_date:2025-04-21 23:36:15.458408+00:00
[2025-04-21T23:36:15.881+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews_pipeline and current dag run status:running
[2025-04-21T23:36:15.882+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-21T23:36:15.900+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-04-21T23:36:15.933+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-21T23:36:15.952+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-21T23:36:15.953+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=google_maps_reviews_pipeline, task_id=model_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250421T233615, end_date=20250421T233615
[2025-04-21T23:36:15.995+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-21T23:36:15.997+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-21T23:36:15.998+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews_pipeline queued_at:2025-04-21 23:35:16.401569+00:00
[2025-04-21T23:36:15.999+0000] {logging_mixin.py:190} INFO - Task hostname:95fe2406fe61 operator:PythonOperator
[2025-04-21T23:36:16.027+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-21T23:36:16.060+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T23:36:16.071+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
